### ISSUE TITLE
[Help Wanted] Run your code but got line 2: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by stephenwang1011** [airicyu/rameter#1]
![image](https://user-images.githubusercontent.com/3350356/164968457-09bb2ce8-792b-4d6e-a114-693790ad88e6.png)

**Comment by stephenwang1011** [comment]
`import { Rameter, HttpRequestSampler, sleep, UserModelConfig } from "rameter";
const rameter = new Rameter();
/**
 * up-lifting
 */
await rameter.runStandalone();

/**
 * define user groups
 */
rameter.defineUserGroup("members");

/**
 * define user test scenario
 */
rameter.defineUserScenario("hello baidu", async ({ globalContext, nodeContext, userContext, userId }) => {
  try {
    // call an HTTP endpoint
    await HttpRequestSampler.request({
      method: "GET",
      url: `https://www.baidu.com`, // replace this with ur endpoint
    });
  } catch (e) {
    console.error(e);
  } finally {
    await sleep(100); // think time
  }
});

await rameter.readyTest(); // Get ready to test

/**
 * Start the load test. Run until test finished.
 */
await rameter.runUntilFinished([
  {
    userModel: UserModelConfig.stepUserForTime({
      maxUsers: 20,
      steps: 10,
      rampUpTime: 10,
      holdTime: 20,
    }),
    userGroups: ["members"],
    scenarios: ["hello baidu"],
  },
]);

/**
 * shutdown
 */
await rameter.down();`

**Comment by stephenwang1011** [comment]
`
import { Rameter, HttpRequestSampler, sleep, UserModelConfig } from "rameter";
const rameter = new Rameter();
/**
 * up-lifting
 */
await rameter.runStandalone();

/**
 * define user groups
 */
rameter.defineUserGroup("members");

/**
 * define user test scenario
 */
rameter.defineUserScenario("hello baidu", async ({ globalContext, nodeContext, userContext, userId }) => {
  try {
    // call an HTTP endpoint
    await HttpRequestSampler.request({
      method: "GET",
      url: `https://www.baidu.com`, // replace this with ur endpoint
    });
  } catch (e) {
    console.error(e);
  } finally {
    await sleep(100); // think time
  }
});

await rameter.readyTest(); // Get ready to test

/**
 * Start the load test. Run until test finished.
 */
await rameter.runUntilFinished([
  {
    userModel: UserModelConfig.stepUserForTime({
      maxUsers: 20,
      steps: 10,
      rampUpTime: 10,
      holdTime: 20,
    }),
    userGroups: ["members"],
    scenarios: ["hello baidu"],
  },
]);

/**
 * shutdown
 */
await rameter.down();
`

**Comment by airicyu** [comment]
Hello @stephenwang1011 ,

The example is using ES module type style.
i.e. in your package.json, u need to have this:
```
"type": "module",
```

Did ur package.json already setting this?

**Comment by stephenwang1011** [comment]
> Hello @stephenwang1011 ,
> 
> The example is using ES module type style. i.e. in your package.json, u need to have this:
> 
> ```
> "type": "module",
> ```
> 
> Did ur package.json already setting this?

it works, thanks

**Comment by airicyu** [comment]
btw, I found some issue with 0.12.1 version for the examples.
you may try to upgrade to 0.12.2 instead as well.

**Comment by stephenwang1011** [comment]
> btw, I found some issue with 0.12.1 version for the examples. you may try to upgrade to 0.12.2 instead as well.

yeah, I did. Thanks so much for providing this powerful   too

**Comment by airicyu** [comment]
just wanna ask a little bit, how do u know about this module actually?

after I publish the module I find that the naming is very bad that it can't easily searched by searching engine.
searching engine would simply show search result for "parameter".
So I wonder why still have people can find this module.

**Comment by stephenwang1011** [comment]
> just wanna ask a little bit, how do u know about this module actually?
> 
> after I publish the module I find that the naming is very bad that it can't easily searched by searching engine. searching engine would simply show search result for "parameter". So I wonder why still have people can find this module.

I found this from NPM（https://www.npmjs.com/）and  the keyword  is  "jmeter" then I found this powerful module
